export const careerData = [
  {
    id: 1,
    title: 'Technology and Innovation Leader @ Alaska Cool',
    date: 'Jul 2023 - Present',
    description:
      'Leading technology initiatives and driving innovation across multiple platforms',
    branch: 'main',
    technologies: ['Python', 'Node.js', 'React', 'Mobile Development', 'SCRUM'],
    achievements: [
      'Led development of backend systems supporting 3 platforms (mobile + 2 web apps)',
      'Integrated Host to Host BAC system, reducing processing time by 40%',
      'Created mobile app for real-time technician task management',
      'Implemented SCRUM methodology, reducing project delivery time by 20%',
      'Automated invoicing process, significantly reducing errors',
    ],
    role: 'Technology and Innovation Leader',
    company: 'Alaska Cool, S.A.',
    duration: 'July 2023 - Present',
  },
  {
    id: 2,
    title: 'Senior Software Developer @ Grupo LAFISE',
    date: 'May 2021 - Jul 2023',
    description:
      'Led technical implementations of international payment solutions',
    branch: 'feature/senior-dev',
    technologies: ['H2H', 'Visa B2B', 'SWIFT GPI', 'Payment Systems'],
    achievements: [
      'Enhanced H2H platform for corporate clients',
      'Implemented Visa B2B and SWIFT GPI Tracker solutions regionally',
      'Managed regional remittance projects serving 50,000+ monthly users',
    ],
    role: 'Senior Software Developer',
    company: 'Grupo LAFISE',
    duration: 'May 2021 - July 2023',
  },
  {
    id: 3,
    title: 'Junior Software Developer @ Grupo LAFISE',
    date: 'Jan 2018 - May 2021',
    description:
      'Developed and integrated banking technologies and payment solutions',
    branch: 'merge/junior-dev',
    technologies: ['Banking Tech', 'Payment Solutions', 'Technical Support'],
    achievements: [
      'Collaborated in development of key banking projects',
      'Integrated new banking technologies',
      'Provided technical support and system enhancements',
    ],
    role: 'Junior Software Developer',
    company: 'Grupo LAFISE',
    duration: 'January 2018 - May 2021',
    mergeFrom: 'feature/senior-dev',
  },
  {
    id: 4,
    title: 'System Developer @ Nestrix',
    date: 'Jan 2017 - Sep 2019',
    description: 'Led development of e-commerce and mobile solutions',
    branch: 'feature/system-dev',
    technologies: ['E-commerce', 'Mobile Development', 'Sales Solutions'],
    achievements: [
      'Developed e-commerce platform',
      'Created mobile app for e-commerce',
      'Optimized operational performance metrics',
    ],
    role: 'System Developer',
    company: 'Nestrix',
    duration: 'January 2017 - September 2019',
  },
  {
    id: 5,
    title: 'CEO and Co-Founder @ CCL-Technologies',
    date: 'Nov 2014 - Sep 2019',
    description:
      'Founded and led technology development company serving major enterprises',
    branch: 'main',
    technologies: ['Enterprise Solutions', 'CRM', 'Custom Development'],
    achievements: [
      'Founded technology company focused on enterprise solutions',
      'Developed solutions for major companies like Tigo and Alaska Cool',
      'Created custom enterprise applications and CRMs',
    ],
    role: 'CEO and Co-Founder',
    company: 'CCL-Technologies',
    duration: 'November 2014 - September 2019',
  },
];
